import { useThemeContext } from '@/context/ThemeContext';
import { Box, Button } from '@kuma-ui/core';
import Head from 'next/head';
import useSWR from 'swr';
import  Header  from '../../modules/Header';
import  Footer  from '../../modules/Footer';
import { Leagues } from '../../modules/Leagues';
import { Events } from '../../modules/Events';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import EventItem from '../../modules/EventItem'; // Import EventItem component

export default function Home() {
  const { setIsDark } = useThemeContext();
  const router = useRouter();
  console.log(router.asPath);

  // Function to format date as yyyy-mm-dd
  const formatDate = (date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  // Get today's date
  const today = new Date();

  const [sportString, setSportString] = useState('football');
  const [eventData, setEventData] = useState(null);
  const [selectedEvent, setSelectedEvent] = useState(null); // State to track the selected event

  useEffect(() => {
    const { sport, date } = router.query;
    const currentPath = router.asPath; // Get current path
    if (currentPath === '/sport/') {
      // Redirect to /sport/football if current path is /sport/
      router.push(`/sport/football/${formatDate(today)}`);
    } else if (!date) {
      // Redirect to /sport/football if sport query parameter is not provided
      router.push(`/sport/${sport}/${formatDate(today)}`);
    }
    
    const sportValue = sport ? (Array.isArray(sport) ? sport[0] : sport) : 'football';
    setSportString(sportValue);
  }, [router.query]);

  let currentDate = formatDate(today);

  // Fetch eventData using useSWR
  const { data: fetchedEventData, error: eventError } = useSWR(`/api/sport/${sportString}/events/${currentDate}`);

  useEffect(() => {
    setEventData(fetchedEventData);
  }, [fetchedEventData]);



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <div style={{ display: 'flex', flexDirection: 'row', padding: '24px 30px', marginTop: '24px' }}>
        <div style={{ marginRight: '30px', flex: '1' }}>
          <Leagues sport={sportString} />
        </div>
        <div style={{ marginRight: '30px', flex: '1' }}>
          {eventData && <Events sport={sportString} eventData={eventData} />} {/* Pass onEventClick prop */}
        </div>
        
      </div>

      <Footer />
    </>
  );
}
